import healthRoutes from "./health.js";
import uploadRoutes from "./uploads.js";
import supplierRoutes from "./suppliers.js";
import klasifikasiRoutes from "./klasifikasi.js";
import merkRoutes from "./merk.js";
import barangRoutes from "./barang.js";
import gudangRoutes from "./gudang.js";
import tokoRoutes from "./toko.js";
import pemindahanRoutes from "./pemindahan.js";
import penerimaanPemindahanRoutes from "./penerimaan-pemindahan.js";
import barcodeManualRoutes from "./barcode-manual.js";
import etalaseRoutes from "./etalase.js";
import kelasHargaRoutes from "./kelas-harga.js";
import channelRoutes from "./channel.js";
import barangKelasHargaRoutes from "./barang-kelas-harga.js";
import hargaJualRequestRoutes from "./harga-jual-request.js";
import channelPricingRuleRoutes from "./channel-pricing-rule.js";
import docCodeRoutes from "./doc-code.js";
import siteRoutes from "./site.js";
import rpoRoutes from "./rpo.js";
import authRoutes from "./auth.js";
import userRoutes from "./users.js";
import dashboardRoutes from "./dashboard.js";
import lpbRoutes from "./lpb.js";
import pengadaanRoutes from "./pengadaan.js";
import tagihanRoutes from "./tagihan.js";
import penerimaanPengadaanRoutes from "./penerimaan-pengadaan.js";
import rekeningSupplierRoutes from "./rekening-supplier.js";
import kontrabonRoutes from "./kontrabon.js";
import promoRoutes from "./promos.js";
import promoVoucherRoutes from "./promo-voucher.js";
import posTransactionRoutes from "./pos-transactions.js";
import mutasiBarangRoutes from "./mutasi-barang.js";
import inquiryStokRoutes from "./inquiry-stok.js";
import rekapanHarianRoutes from "./rekapan-harian.js";
import customerRoutes from "./customers.js";
import returSupplierRoutes from "./retur-supplier.js";

export default async function routes(fastify) {
  fastify.register(healthRoutes);
  fastify.register(uploadRoutes, { prefix: "/uploads" });
  fastify.register(supplierRoutes, { prefix: "/suppliers" });
  fastify.register(klasifikasiRoutes, { prefix: "/klasifikasi" });
  fastify.register(merkRoutes, { prefix: "/merk" });
  fastify.register(barangRoutes, { prefix: "/barang" });
  fastify.register(gudangRoutes, { prefix: "/gudang" });
  fastify.register(tokoRoutes, { prefix: "/toko" });
  fastify.register(pemindahanRoutes, { prefix: "/pemindahan" });
  fastify.register(penerimaanPemindahanRoutes, { prefix: "/penerimaan-pemindahan" });
  fastify.register(barcodeManualRoutes, { prefix: "/barcode-manual" });
  fastify.register(etalaseRoutes, { prefix: "/etalase" });
  fastify.register(kelasHargaRoutes, { prefix: "/kelas-harga" });
  fastify.register(channelRoutes, { prefix: "/channel" });
  fastify.register(barangKelasHargaRoutes, { prefix: "/barang-kelas-harga" });
  fastify.register(barangKelasHargaRoutes, { prefix: "/barang-harga-jual" });
  fastify.register(hargaJualRequestRoutes, { prefix: "/harga-jual-request" });
  fastify.register(channelPricingRuleRoutes, { prefix: "/channel-pricing-rule" });
  fastify.register(docCodeRoutes, { prefix: "/doc-code" });
  fastify.register(siteRoutes, { prefix: "/site" });
  fastify.register(rpoRoutes, { prefix: "/rpo" });
  fastify.register(authRoutes, { prefix: "/auth" });
  fastify.register(userRoutes, { prefix: "/users" });
  fastify.register(dashboardRoutes, { prefix: "/dashboard" });
  fastify.register(lpbRoutes, { prefix: "/lpb" });
  fastify.register(pengadaanRoutes, { prefix: "/pengadaan" });
  fastify.register(tagihanRoutes, { prefix: "/tagihan" });
  fastify.register(penerimaanPengadaanRoutes, { prefix: "/penerimaan-pengadaan" });
  fastify.register(rekeningSupplierRoutes, { prefix: "/rekening-supplier" });
  fastify.register(kontrabonRoutes, { prefix: "/kontrabon" });
  fastify.register(promoRoutes, { prefix: "/promos" });
  fastify.register(promoVoucherRoutes, { prefix: "/promos/voucher" });
  fastify.register(posTransactionRoutes, { prefix: "/pos" });
  fastify.register(mutasiBarangRoutes, { prefix: "/mutasi-barang" });
  fastify.register(inquiryStokRoutes, { prefix: "/inquiry-stok" });
  fastify.register(rekapanHarianRoutes, { prefix: "/rekapan-harian" });
  fastify.register(customerRoutes, { prefix: "/customers" });
  fastify.register(returSupplierRoutes, { prefix: "/retur-supplier" });
}
